# Generated by Django 4.2 on 2026-03-08 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_dealerapplication_userprofile_dealerreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=15)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('is_processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dealer', models.ForeignKey(blank=True, help_text='Auto-assigned based on vehicle or city', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.dealerprofile')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.vehicle')),
            ],
            options={
                'verbose_name': 'Public Enquiry',
                'verbose_name_plural': 'Public Enquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
