# Generated by Django 4.2 on 2026-03-08 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_publicenquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealerprofile',
            name='plan_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dealerprofile',
            name='plan_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dealerprofile',
            name='plan_type',
            field=models.CharField(choices=[('free', 'Free Trial'), ('pro', 'Pro')], default='free', max_length=20),
        ),
    ]
