# Generated by Django 4.2 on 2026-03-09 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_dealerprofile_plan_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealerprofile',
            name='notify_email',
            field=models.BooleanField(default=True, help_text='Receive email notifications'),
        ),
        migrations.AddField(
            model_name='dealerprofile',
            name='notify_push',
            field=models.BooleanField(default=True, help_text='Receive push notifications'),
        ),
        migrations.AddField(
            model_name='dealerprofile',
            name='notify_whatsapp',
            field=models.BooleanField(default=True, help_text='Receive WhatsApp notifications'),
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp'), ('push', 'Push Notification'), ('sms', 'SMS')], max_length=20)),
                ('notif_type', models.CharField(choices=[('welcome', 'Welcome'), ('approval', 'Dealer Approved'), ('rejection', 'Dealer Rejected'), ('plan_expiry', 'Plan Expiry Warning'), ('new_lead', 'New Lead'), ('new_enquiry', 'New Enquiry'), ('emi_due', 'EMI Due Reminder'), ('delivery', 'Delivery Reminder'), ('offer', 'Offer Broadcast'), ('other', 'Other')], default='other', max_length=30)),
                ('recipient', models.CharField(help_text='Email or phone number', max_length=200)),
                ('subject', models.CharField(blank=True, max_length=300)),
                ('success', models.BooleanField(default=False)),
                ('error_msg', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('dealer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to='api.dealerprofile')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
    ]
