# Generated by Django 4.2 on 2026-03-10 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_dealerprofile_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(choices=[('walk_in', 'Walk-in'), ('phone', 'Phone Inquiry'), ('website', 'Website Lead'), ('referral', 'Referral'), ('social', 'Social Media'), ('marketplace', 'Marketplace Enquiry'), ('review', 'Buyer Review')], default='website', max_length=20),
        ),
    ]
