# Generated by Django 4.2 on 2026-03-10 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_lead_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='chassis_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='sale',
            name='engine_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='sale',
            name='place_of_supply',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sale',
            name='vehicle_color',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='sale',
            name='year_of_manufacture',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
