# Generated by Django 4.2 on 2026-03-10 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_sale_chassis_number_sale_engine_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealerprofile',
            name='bank_account_number',
            field=models.CharField(blank=True, default='50200012345678', max_length=50),
        ),
        migrations.AddField(
            model_name='dealerprofile',
            name='bank_ifsc',
            field=models.CharField(blank=True, default='HDFC000123', max_length=20),
        ),
        migrations.AddField(
            model_name='dealerprofile',
            name='bank_name',
            field=models.CharField(blank=True, default='HDFC Bank Ltd.', max_length=200),
        ),
        migrations.AddField(
            model_name='dealerprofile',
            name='bank_upi',
            field=models.CharField(blank=True, default='erikshawdekho@hdfc', max_length=100),
        ),
        migrations.AddField(
            model_name='dealerprofile',
            name='invoice_footer_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='dealerprofile',
            name='sales_manager_name',
            field=models.CharField(blank=True, default='Authorised Signatory', max_length=200),
        ),
        migrations.AddField(
            model_name='sale',
            name='battery_capacity_ah',
            field=models.CharField(blank=True, help_text='e.g. 100Ah 48V', max_length=50),
        ),
        migrations.AddField(
            model_name='sale',
            name='battery_make',
            field=models.CharField(blank=True, help_text='e.g. Amara Raja, Exide', max_length=100),
        ),
        migrations.AddField(
            model_name='sale',
            name='battery_serial_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sale',
            name='battery_warranty_months',
            field=models.IntegerField(blank=True, help_text='Battery warranty in months', null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='motor_serial_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sale',
            name='vehicle_warranty_months',
            field=models.IntegerField(blank=True, help_text='Vehicle/chassis warranty in months', null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='cgst_rate',
            field=models.DecimalField(decimal_places=2, default=2.5, max_digits=5),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sgst_rate',
            field=models.DecimalField(decimal_places=2, default=2.5, max_digits=5),
        ),
    ]
