# Generated by Django 4.2 on 2026-03-10 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_dealerprofile_bank_account_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='battery_count',
            field=models.IntegerField(default=1, help_text='Number of battery units installed'),
        ),
        migrations.AddField(
            model_name='sale',
            name='financer_details',
            field=models.TextField(blank=True, help_text='Financer name, loan a/c, ref number, branch etc.'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='customer_name',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='lead',
            name='phone',
            field=models.CharField(db_index=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='sale',
            name='customer_name',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='sale',
            name='customer_phone',
            field=models.CharField(db_index=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='sale',
            name='invoice_number',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
    ]
