# Generated by Django 4.2 on 2026-03-10 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_sale_battery_count_financer_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('youtube_url', models.URLField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('tutorial', 'How to Drive'), ('maintenance', 'Maintenance Tips'), ('earning', 'Earn More'), ('review', 'Expert Review'), ('general', 'General Info')], default='general', max_length=20)),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dealer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='api.dealerprofile')),
            ],
        ),
    ]
