# Generated by Django 4.2 on 2026-03-10 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_video_resource'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='thumbnail_url',
            field=models.URLField(blank=True, help_text='External image URL for seeded/demo vehicles', max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('excerpt', models.TextField(blank=True, help_text='Short description shown in card')),
                ('content', models.TextField(blank=True, help_text='Full article content (optional)')),
                ('url', models.URLField(blank=True, help_text='External article URL', max_length=500)),
                ('category', models.CharField(choices=[('maintenance', 'Maintenance Tips'), ('earning', 'Earn More'), ('news', 'Industry News'), ('scheme', 'Government Schemes'), ('general', 'General')], default='general', max_length=20)),
                ('cover_image_url', models.URLField(blank=True, max_length=500)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dealer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to='api.dealerprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
