# Generated by Django 4.2 on 2026-03-10 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_blog_post_and_vehicle_thumbnail_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.CharField(max_length=50, unique=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('listing_limit', models.IntegerField(default=3, help_text='Max vehicle listings. 0 = unlimited.')),
                ('priority_ranking', models.BooleanField(default=False)),
                ('featured_badge', models.BooleanField(default=False)),
                ('whatsapp_alerts', models.BooleanField(default=False)),
                ('analytics_access', models.BooleanField(default=False)),
                ('yearly_subscription', models.BooleanField(default=False)),
                ('max_dealers', models.IntegerField(default=0, help_text='Max dealers on this plan. 0 = unlimited.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='dealerprofile',
            name='listing_count',
            field=models.IntegerField(default=0, help_text='Cached count of active listings'),
        ),
        migrations.AddField(
            model_name='lead',
            name='buyer_latitude',
            field=models.FloatField(blank=True, help_text='Buyer GPS latitude', null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='buyer_longitude',
            field=models.FloatField(blank=True, help_text='Buyer GPS longitude', null=True),
        ),
        migrations.AddField(
            model_name='dealerprofile',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dealers', to='api.plan'),
        ),
    ]
