# Generated by Django 4.2 on 2026-03-13 08:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0014_dealer_api_key_platform_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealerprofile',
            name='invoice_count',
            field=models.IntegerField(default=0, help_text='Invoices generated (free tier limit: 20)'),
        ),
        migrations.AddField(
            model_name='dealerprofile',
            name='lifetime_lead_count',
            field=models.IntegerField(default=0, help_text='Lifetime leads received (free tier limit: 50)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('driver', 'Driver / Buyer'), ('dealer', 'Dealer / Showroom'), ('admin', 'Platform Admin'), ('financer', 'Financer / NBFC'), ('customer', 'Customer / Buyer')], default='dealer', max_length=20),
        ),
        migrations.CreateModel(
            name='FinancerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('contact_person', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('gstin', models.CharField(blank=True, max_length=20)),
                ('pan_number', models.CharField(blank=True, max_length=12)),
                ('description', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='financers/')),
                ('is_verified', models.BooleanField(default=False)),
                ('interest_rate_min', models.DecimalField(decimal_places=2, default=8.0, max_digits=5)),
                ('interest_rate_max', models.DecimalField(decimal_places=2, default=18.0, max_digits=5)),
                ('max_loan_amount', models.DecimalField(decimal_places=2, default=500000, max_digits=12)),
                ('min_loan_amount', models.DecimalField(decimal_places=2, default=50000, max_digits=12)),
                ('max_tenure_months', models.IntegerField(default=60)),
                ('processing_fee_pct', models.DecimalField(decimal_places=2, default=2.0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='financer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FinancerDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('registration', 'Company Registration'), ('pan', 'PAN Card'), ('gst', 'GST Certificate'), ('rbi_license', 'RBI / NBFC License'), ('address_proof', 'Address Proof'), ('bank_statement', 'Bank Statement'), ('agreement', 'Partnership Agreement'), ('other', 'Other')], default='other', max_length=30)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('file', models.FileField(upload_to='financer_docs/')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('financer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='api.financerprofile')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=15)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('pincode', models.CharField(blank=True, max_length=10)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
