# Generated by Django 4.2 on 2026-03-13 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_financer_customer_profiles_free_tier'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_phone', models.CharField(max_length=15)),
                ('customer_email', models.EmailField(blank=True, max_length=254)),
                ('customer_address', models.TextField(blank=True)),
                ('customer_aadhaar', models.CharField(blank=True, max_length=20)),
                ('customer_pan', models.CharField(blank=True, max_length=12)),
                ('customer_dob', models.DateField(blank=True, null=True)),
                ('vehicle_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('down_payment', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tenure_months', models.IntegerField(default=36)),
                ('status', models.CharField(choices=[('draft', 'Draft — Collecting Documents'), ('submitted', 'Submitted to Financer'), ('under_review', 'Under Review'), ('docs_required', 'Additional Documents Required'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('disbursed', 'Loan Disbursed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('status_notes', models.TextField(blank=True, help_text='Financer notes visible to dealer on status update.')),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_applications', to='api.dealerprofile')),
                ('financer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_applications', to='api.financerprofile')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.vehicle')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FinancerPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.CharField(max_length=50, unique=True)),
                ('price_per_year', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('max_dealer_associations', models.IntegerField(default=0, help_text='Max dealers this financer can onboard. 0 = unlimited.')),
                ('max_finance_applications', models.IntegerField(default=10, help_text='Free tier: 10 applications before upgrade required.')),
                ('success_commission_pct', models.DecimalField(decimal_places=2, default=0, help_text='Platform commission % charged on successful loan disbursement.', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('features_json', models.JSONField(blank=True, default=list, help_text='List of feature strings to display on plan card.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['price_per_year'],
            },
        ),
        migrations.AddField(
            model_name='publicenquiry',
            name='brand_name',
            field=models.CharField(blank=True, help_text='Brand selected by driver during enquiry', max_length=100),
        ),
        migrations.AddField(
            model_name='publicenquiry',
            name='pincode',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='publicenquiry',
            name='dealer',
            field=models.ForeignKey(blank=True, help_text='Targeted dealer selected by driver. Lead goes only to this dealer.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.dealerprofile'),
        ),
        migrations.CreateModel(
            name='FinancerSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('applications_used', models.IntegerField(default=0, help_text='Financed applications this billing cycle (free tier limit enforced).')),
                ('auto_renew', models.BooleanField(default=False)),
                ('financer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='api.financerprofile')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.financerplan')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='FinanceApplicationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(help_text='Must match one of FinancerRequiredDocument.doc_type choices.', max_length=30)),
                ('file', models.FileField(upload_to='finance_app_docs/')),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='api.financeapplication')),
            ],
        ),
        migrations.CreateModel(
            name='FinancerRequiredDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('aadhaar', 'Aadhaar Card'), ('pan', 'PAN Card'), ('voter_id', 'Voter ID'), ('driving_license', 'Driving License'), ('bank_statement', 'Bank Statement (3 months)'), ('income_proof', 'Income / Salary Proof'), ('address_proof', 'Address Proof'), ('passport_photo', 'Passport Size Photo (2 copies)'), ('vehicle_quotation', 'Vehicle Quotation from Dealer'), ('form_16', 'Form 16 / ITR'), ('other', 'Other')], max_length=30)),
                ('description', models.CharField(blank=True, help_text='Additional instructions for this document.', max_length=300)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('financer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_documents', to='api.financerprofile')),
            ],
            options={
                'ordering': ['doc_type'],
                'unique_together': {('financer', 'doc_type')},
            },
        ),
        migrations.CreateModel(
            name='FinancerDealerAssociation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending Financer Approval'), ('approved', 'Approved by Financer'), ('rejected', 'Rejected by Financer'), ('suspended', 'Suspended')], default='pending', max_length=20)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financer_associations', to='api.dealerprofile')),
                ('financer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dealer_associations', to='api.financerprofile')),
            ],
            options={
                'ordering': ['-applied_at'],
                'unique_together': {('financer', 'dealer')},
            },
        ),
    ]
