# Generated by Django 4.2 on 2026-03-14 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_financer_ecosystem_finance_applications'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='financeloan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='sale',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='sale',
            name='sale_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='task',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['dealer', 'phone'], name='api_custome_dealer__0d4865_idx'),
        ),
        migrations.AddIndex(
            model_name='financeapplication',
            index=models.Index(fields=['dealer', 'status'], name='api_finance_dealer__8dfa02_idx'),
        ),
        migrations.AddIndex(
            model_name='financeapplication',
            index=models.Index(fields=['financer', 'status'], name='api_finance_finance_b37d7d_idx'),
        ),
        migrations.AddIndex(
            model_name='financeloan',
            index=models.Index(fields=['dealer', 'status'], name='api_finance_dealer__943a43_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['dealer', 'status'], name='api_lead_dealer__c1dcab_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['created_at'], name='api_lead_created_1467d6_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['dealer', 'sent_at'], name='api_notific_dealer__826216_idx'),
        ),
        migrations.AddIndex(
            model_name='publicenquiry',
            index=models.Index(fields=['dealer', 'is_processed'], name='api_publice_dealer__88c700_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['dealer', 'sale_date'], name='api_sale_dealer__acf1be_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['dealer', 'is_active', 'stock_status'], name='api_vehicle_dealer__1e2915_idx'),
        ),
    ]
