# Generated by Django 4.2 on 2026-03-16 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_db_best_practices'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealerprofile',
            name='lifetime_enquiry_count',
            field=models.IntegerField(default=0, help_text='Lifetime public enquiries received (free tier limit: 20)'),
        ),
        migrations.AlterField(
            model_name='dealerprofile',
            name='lifetime_lead_count',
            field=models.IntegerField(default=0, help_text='Lifetime leads received (free tier limit: 20)'),
        ),
    ]
