# Generated by Django 4.2 on 2026-03-17 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_add_lifetime_enquiry_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='down_payment',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Customer down payment amount', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='loan_amount_financed',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount financed via loan', max_digits=10, null=True),
        ),
    ]
