# Generated by Django 4.2 on 2026-03-17 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_add_sale_loan_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financerplan',
            name='success_commission_pct',
        ),
        migrations.AddField(
            model_name='financerplan',
            name='commission_per_lead',
            field=models.DecimalField(decimal_places=2, default=3000, help_text='Platform commission charged per successfully financed lead (₹).', max_digits=10),
        ),
        migrations.AlterField(
            model_name='financerplan',
            name='max_dealer_associations',
            field=models.IntegerField(default=2, help_text='Max dealers financer can add. 0 = unlimited.'),
        ),
        migrations.AlterField(
            model_name='financerplan',
            name='max_finance_applications',
            field=models.IntegerField(default=5, help_text='Max lifetime applications. 0 = unlimited.'),
        ),
    ]
