# Generated by Django 4.2 on 2026-03-17 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_financer_plan_commission'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='lead',
            name='api_lead_created_1467d6_idx',
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['dealer', 'created_at'], name='api_lead_dealer__dc66c7_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['dealer', 'is_deleted'], name='api_lead_dealer__86ae7e_idx'),
        ),
    ]
