# Generated by Django 4.2 on 2026-03-17 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_finance_application_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealerprofile',
            name='is_demo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='financerprofile',
            name='is_demo',
            field=models.BooleanField(default=False),
        ),
    ]
