# Generated by Django 4.2 on 2026-03-18 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_add_is_demo_to_profiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='announcement_link',
            field=models.URLField(blank=True, default='', help_text='Optional link for the announcement bar.'),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='announcement_text',
            field=models.CharField(blank=True, default='', help_text='Top announcement bar text. Leave blank to hide.', max_length=300),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='hero_subtitle_en',
            field=models.CharField(blank=True, default='Get best prices directly from verified dealers across India — completely free', help_text='Hero subtitle in English', max_length=300),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='hero_subtitle_hi',
            field=models.CharField(blank=True, default='भारत के verified dealers से सीधे best price पाएँ — बिल्कुल मुफ्त', help_text='Hero subtitle in Hindi', max_length=300),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='hero_title_en',
            field=models.CharField(blank=True, default='Looking for E-Rickshaw?', help_text='Hero heading in English', max_length=200),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='hero_title_hi',
            field=models.CharField(blank=True, default='ई-रिक्शा चाहिए?', help_text='Hero heading in Hindi', max_length=200),
        ),
    ]
