# Generated by Django 4.2 on 2026-03-18 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_vehicle_type_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='payload_kg',
            field=models.CharField(blank=True, help_text='e.g. 500 or 600-1000 kg', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='seating_capacity',
            field=models.CharField(blank=True, default='3', help_text='e.g. 3, 4+1, 3+1', max_length=20),
        ),
    ]
