# Generated by Django 4.2 on 2026-03-19 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_seating_payload_charfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='range_km',
            field=models.CharField(blank=True, help_text='e.g. 120 or 100-120 km', max_length=30, null=True),
        ),
    ]
