# Generated by Django 4.2 on 2026-03-19 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_range_km_charfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='max_speed',
            field=models.CharField(blank=True, help_text='e.g. 45 or 45-55 km/h', max_length=30, null=True),
        ),
    ]
