# Generated by Django 4.2 on 2026-03-19 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_max_speed_charfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealerprofile',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Store banner/cover image shown in dealer directory', null=True, upload_to='dealers/covers/'),
        ),
        migrations.AlterField(
            model_name='dealerprofile',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='dealers/logos/'),
        ),
    ]
