# Generated by Django 4.2 on 2026-03-20 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_dealer_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='stock_quantity',
            field=models.IntegerField(default=1),
        ),
    ]
