# Generated by Django 4.2 on 2026-03-07 17:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brands/')),
                ('website', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('gstin', models.CharField(blank=True, max_length=20)),
                ('total_purchases', models.IntegerField(default=0)),
                ('total_spent', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DealerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dealer_name', models.CharField(max_length=200)),
                ('gstin', models.CharField(blank=True, max_length=20)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(default='Delhi', max_length=100)),
                ('state', models.CharField(default='Delhi', max_length=100)),
                ('pincode', models.CharField(blank=True, max_length=10)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='dealers/')),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dealer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('source', models.CharField(choices=[('walk_in', 'Walk-in'), ('phone', 'Phone Inquiry'), ('website', 'Website Lead'), ('referral', 'Referral'), ('social', 'Social Media')], default='website', max_length=20)),
                ('status', models.CharField(choices=[('new', 'New'), ('interested', 'Interested'), ('follow_up', 'Follow Up'), ('converted', 'Converted'), ('lost', 'Lost')], default='new', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='api.dealerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=200)),
                ('vehicle_type', models.CharField(choices=[('passenger', 'Passenger Rickshaw'), ('cargo', 'Cargo Loader'), ('auto', 'Auto Rickshaw')], default='passenger', max_length=20)),
                ('fuel_type', models.CharField(choices=[('electric', 'Electric'), ('petrol', 'Petrol'), ('cng', 'CNG'), ('lpg', 'LPG'), ('diesel', 'Diesel')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_quantity', models.IntegerField(default=0)),
                ('stock_status', models.CharField(choices=[('in_stock', 'In Stock'), ('low_stock', 'Low Stock'), ('out_of_stock', 'Out of Stock')], default='in_stock', max_length=20)),
                ('year', models.IntegerField(default=2024)),
                ('is_used', models.BooleanField(default=False)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='vehicles/')),
                ('range_km', models.IntegerField(blank=True, help_text='Range in KM (for electric)', null=True)),
                ('battery_capacity', models.CharField(blank=True, max_length=50)),
                ('max_speed', models.IntegerField(blank=True, null=True)),
                ('payload_kg', models.IntegerField(blank=True, null=True)),
                ('seating_capacity', models.IntegerField(default=3)),
                ('warranty_years', models.IntegerField(default=1)),
                ('hsn_code', models.CharField(default='8703', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.brand')),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='api.dealerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='api.dealerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_phone', models.CharField(max_length=15)),
                ('customer_email', models.EmailField(blank=True, max_length=254)),
                ('customer_address', models.TextField(blank=True)),
                ('customer_gstin', models.CharField(blank=True, max_length=20)),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField(default=1)),
                ('cgst_rate', models.DecimalField(decimal_places=2, default=9.0, max_digits=5)),
                ('sgst_rate', models.DecimalField(decimal_places=2, default=9.0, max_digits=5)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('loan', 'Loan / Finance'), ('upi', 'UPI'), ('bank_transfer', 'Bank Transfer'), ('cheque', 'Cheque')], default='cash', max_length=20)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('is_delivered', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('sale_date', models.DateTimeField(auto_now_add=True)),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='api.dealerprofile')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.lead')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.vehicle')),
            ],
        ),
        migrations.AddField(
            model_name='lead',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.vehicle'),
        ),
        migrations.CreateModel(
            name='FinanceLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200)),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tenure_months', models.IntegerField(default=36)),
                ('interest_rate', models.DecimalField(decimal_places=2, default=12.0, max_digits=5)),
                ('emi_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('disbursed', 'Disbursed')], default='pending', max_length=20)),
                ('applied_date', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.customer')),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='api.dealerprofile')),
                ('vehicle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.vehicle')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='dealer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='api.dealerprofile'),
        ),
    ]
